# Generated by Django 3.2.3 on 2021-05-19 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20210518_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='data_placing',
            new_name='date_placing',
        ),
    ]
