# Generated by Django 3.2.3 on 2021-05-20 20:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_rename_data_placing_plan_date_placing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='g2021',
            field=models.PositiveIntegerField(default=0, verbose_name='2021'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='g2022',
            field=models.PositiveIntegerField(default=0, verbose_name='2022'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='g2023',
            field=models.PositiveIntegerField(default=0, verbose_name='2023'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='g2024',
            field=models.PositiveIntegerField(default=0, verbose_name='2024'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='info_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Сведения о количестве'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='info_start_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Начальная цена'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='next',
            field=models.PositiveIntegerField(default=0, verbose_name='Последующие'),
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_contract', models.TextField(verbose_name='Предмет договора')),
                ('source_finance', models.CharField(max_length=40, verbose_name='Источник финансирования')),
                ('executor', models.CharField(max_length=255, verbose_name='Испольнитель')),
                ('number_contract', models.CharField(max_length=100, verbose_name='Номер договора')),
                ('date_contract', models.DateField(default=datetime.date.today, verbose_name='Дата договора')),
                ('term_execution', models.DateField(default=datetime.date.today, verbose_name='Срок исполнения')),
                ('add_agreement', models.CharField(max_length=255, verbose_name='Дополнительное соглашение')),
                ('fact_price', models.PositiveIntegerField(default=0, verbose_name='Фактическая сумма')),
                ('fact_price1', models.PositiveIntegerField(default=0, verbose_name='Фактическая сумма 1 год')),
                ('fact_price2', models.PositiveIntegerField(default=0, verbose_name='Фактическая сумма 2 год')),
                ('fact_price3', models.PositiveIntegerField(default=0, verbose_name='Фактическая сумма 3 год')),
                ('fact_price4', models.PositiveIntegerField(default=0, verbose_name='Фактическая сумма 4 год')),
                ('fact_next', models.PositiveIntegerField(default=0, verbose_name='Фактическая сумма последующие года')),
                ('payment_year1', models.PositiveIntegerField(default=0, verbose_name='Оплата 1 год')),
                ('payment_year2', models.PositiveIntegerField(default=0, verbose_name='Оплата 2 год')),
                ('payment_year3', models.PositiveIntegerField(default=0, verbose_name='Оплата 3 год')),
                ('payment_year4', models.PositiveIntegerField(default=0, verbose_name='Оплата 4 год')),
                ('payment_next', models.PositiveIntegerField(default=0, verbose_name='Оплата последующие года')),
                ('consignment_note', models.CharField(max_length=255, verbose_name='Товарная накладная')),
                ('payment_order', models.CharField(max_length=255, verbose_name='Платежное поручение')),
                ('kvr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.spr1_kvr', verbose_name='КВР')),
            ],
            options={
                'verbose_name': 'Факт',
                'verbose_name_plural': 'Факт',
            },
        ),
    ]
