# Generated by Django 3.2.3 on 2021-05-21 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20210520_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='add_agreement',
            field=models.CharField(max_length=255, null=True, verbose_name='Дополнительное соглашение'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='consignment_note',
            field=models.CharField(max_length=255, null=True, verbose_name='Товарная накладная'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='executor',
            field=models.CharField(max_length=255, null=True, verbose_name='Испольнитель'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='kvr',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.spr1_kvr', verbose_name='КВР'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='name_contract',
            field=models.TextField(null=True, verbose_name='Предмет договора'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='number_contract',
            field=models.CharField(max_length=100, null=True, verbose_name='Номер договора'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='payment_order',
            field=models.CharField(max_length=255, null=True, verbose_name='Платежное поручение'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='source_finance',
            field=models.CharField(max_length=40, null=True, verbose_name='Источник финансирования'),
        ),
    ]
