# Generated by Django 3.2.3 on 2021-05-21 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20210521_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='kvr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.spr1_kvr', verbose_name='КВР'),
        ),
    ]
