# Generated by Django 3.2.3 on 2021-05-22 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_alter_fact_kvr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact_pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Сумма')),
                ('year', models.CharField(max_length=25, verbose_name='Год')),
                ('consignment_note', models.CharField(max_length=255, null=True, verbose_name='Товарная накладная')),
                ('payment_order', models.CharField(max_length=255, null=True, verbose_name='Платежное поручение')),
                ('id_fact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.fact', verbose_name='Факт')),
            ],
            options={
                'verbose_name': 'Оплата по годам',
                'verbose_name_plural': 'Оплата по годам',
            },
        ),
    ]
